### PR TITLE
Create CODE_OF_CONDUCT.md

### LINKED ISSUE #3: Add CODE_OF_CONDUCT.md
I need an custom Code of Conduct file to be added to the following repository.

Adapt the CODE OF CONDUCT from here ----> https://www.contributor-covenant.org/version/2/0/code_of_conduct/

### PR DESCRIPTION
**Pull request by Nikhil-1503**
Fixes #3 

Added Code of conduct file

### CODE REVIEW

**Comment by Agrover112** [comment]
@Nikhil-1503  this might be hijacking someone else's PR. So it's duplicate pls checkout other Issues

**Comment by Nikhil-1503** [comment]
> @Nikhil-1503 this might be hijacking someone else's PR. So it's duplicate pls checkout other Issues

But I was assigned to this issue though.

**Comment by Agrover112** [comment]
@Nikhil-1503  Oh,no I messed up .

**Comment by Agrover112** [comment]
@Nikhil-1503  Can you check my bash_utils repository for adding any PRs.

**Comment by Nikhil-1503** [comment]
Sure, no problem :)

**Pull request closed without merging**
